---
# tasks file for ocp-install-build-config

- name: "{{ role_name }} | Create Directory Structure"
  file:
    path: "{{ item }}"
    state: directory
    mode: "0744"
  with_items:
    - "{{ secrets_dir }}"
    - "{{ cluster_configs_dir }}"

- name: "{{ role_name }} | Generate Deployment Keys"
  openssh_keypair:
    path: "{{ secrets_dir }}/id_rsa_kubeadmin"
    comment: "core@ocp.kubeadmin"
  
- name: "{{ role_name }} | Check if Install Type is Baremetal"
  set_fact:
    config_template: "baremetal-install-config"
  when: install_type == "baremetal"
    

- name: "{{ role_name }} | Generate the OpenShift install-config.yaml"
  template:
    src: "{{ config_template }}.yaml.j2"
    dest: "{{ cluster_configs_dir }}/install-config.yaml"